Update main.yml
added another error run line for failing the buid

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,3 +10,5 @@ jobs:
             - uses: actions/checkout@v3
             - name: "Build command"
               run: echo "This workflow run successfully for this partiular action"
+            - name: "making error/failure"
+              run: echo "This is wanted error"; exit 1
